#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c
#Set the build environment
env:
  global:
    - INCLUDE=addons/sourcemod/scripting/include
    - SCRIPTING=addons/sourcemod/scripting
    - PLUGINS=addons/sourcemod/plugins
  matrix:
    - SMVERSION=1.9
    - SMVERSION=1.10
    - SMVERSION=1.11

matrix:
  allow_failures:
    - env: SMVERSION=1.11

install:
    # Sourcemod download
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - chmod +x $SCRIPTING/spcomp
    - mkdir $SCRIPTING/compiled
script:
    - ls -lR
    - $SCRIPTING/spcomp -E -o$SCRIPTING'/compiled/VIP_Core' -v0 $SCRIPTING'/VIP_Core.sp'

#Release
before_deploy:
    - mkdir -p vip
    - ls -lR
    - mv $SCRIPTING/VIP_Core.sp VIP_Core/$SCRIPTING
    - mv $SCRIPTING/vip vip/$SCRIPTING
    - mv $SCRIPTING/compiled/* vip/$PLUGINS
    - mv $INCLUDE/vip_core.inc vip/$INCLUDE
    - rsync -a --prune-empty-dirs --include '*/' --include 'vip*' --exclude '*' addons/sourcemod/translations/ shop/addons/sourcemod/translations/
    - mv addons/sourcemod/configs/shop* shop/addons/sourcemod/configs
    - zip -rq vip vip
    - tar -czf VIP_Core.tar.gz vip
deploy:
    provider: releases
    api_key: ${GH_TOKEN}
    file:
      - VIP_Core.zip
      - VIP_Core.tar.gz
    skip_cleanup: true
    on:
       tags: true
#Notifications
notifications:
    email: false
